server:
  port: 8888

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/dingding
      username: root
      password: ''

  output:
    ansi:
      enabled: always

management:
  endpoints:
    web:
      exposure:
        include: '*'    #以web方式暴露所有节点。在java——console中jmx能获取所有节点