server:
  port: 8888

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/dingding
      username: root
      password: ''

  output:
    ansi:
      enabled: always

#management是所有acturator的配置
#managerment.endpoint.端点名.xxxx 对某个端点具体配置
management:
  endpoints:
    web:
      exposure:
        include: '*'    #以web方式暴露所有节点。在java——console中jmx能获取所有节点
    enabled-by-default: false   #禁用所有端点
  endpoint:
    health:
      show-details: always    #设置成总是显示详细信息。不然只有up和down，不能看到端口或者到底是数据库出问题了？
      enabled: true
    info:
      enabled: true     #单独开放想要访问的端点
    metrics:
      enabled: true
info:
  appName: '自己乱写的'
  appVersion: '1.2'
#  mvPro: @project.build.sourceEncoding@     #需要设置pom.resource--有问题