mycar:
  brand: niubi
  price: 111
#spring:
#  mvc:
#    static-path-pattern: /res/**  #设置了访问前缀欢迎页面有问题。主要是为了方便拦截器
#  web:
#    resources:
#      static-locations: classpath:/res/
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true

#文件上传大小限制
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

#数据库相关
  datasource:
    url: jdbc:mysql://localhost:3306/rfmx
    password: ''
    driver-class-name: com.mysql.jdbc.Driver
    username: root

#druid监控
    druid:
      stat-view-servlet:
        enabled: true
        resetEnable: 'false'

      web-stat-filter:
        enabled: true
        url-pattern: '/*'
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      filters: 'stat,wall'
      filter:
        stat:
          enabled: true
          log-slow-sql: true
        wall:
          enabled: true

      aop-patterns: ['com.atguigu.boot.*']

#开启视图解析器
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
#原生数据库查询超时
  jdbc:
    template:
      query-timeout: 3
#控制台输出颜色
  output:
    ansi:
      enabled: always
server:
  port: 8901

#配置mybatis两个规则
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml